#!/usr/bin/env bash
set -euo pipefail

REPO_RAW_BASE="https://raw.githubusercontent.com/ORyong/vps-traffic-guard/master"
INSTALL_BIN="/usr/local/bin/vps-traffic-monitor"
CONFIG_FILE="/etc/vps-traffic-monitor.env"
CRON_MARK_BEGIN="# BEGIN vps-traffic-guard"
CRON_MARK_END="# END vps-traffic-guard"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'ERROR: missing command: %s\n' "$1" >&2
    exit 1
  }
}

run_as_root() {
  if [[ "$(id -u)" -eq 0 ]]; then
    "$@"
  elif command -v sudo >/dev/null 2>&1; then
    sudo "$@"
  else
    printf 'ERROR: this installer needs root privileges. Re-run as root or install sudo.\n' >&2
    exit 1
  fi
}

prompt_default() {
  local var_name="$1"
  local label="$2"
  local default_value="$3"
  local value
  read -r -p "$label [$default_value]: " value
  if [[ -z "$value" ]]; then
    value="$default_value"
  fi
  printf -v "$var_name" '%s' "$value"
}

prompt_required() {
  local var_name="$1"
  local label="$2"
  local value
  while true; do
    read -r -p "$label: " value
    if [[ -n "$value" ]]; then
      printf -v "$var_name" '%s' "$value"
      return 0
    fi
    printf 'This value is required.\n'
  done
}

is_minute() {
  case "${1:-}" in
    ''|*[!0-9]*) return 1 ;;
    *) (( $1 >= 0 && $1 <= 59 )) ;;
  esac
}

is_hour() {
  case "${1:-}" in
    ''|*[!0-9]*) return 1 ;;
    *) (( $1 >= 0 && $1 <= 23 )) ;;
  esac
}

is_weekday() {
  case "${1:-}" in
    ''|*[!0-9]*) return 1 ;;
    *) (( $1 >= 1 && $1 <= 7 )) ;;
  esac
}

is_monthday() {
  case "${1:-}" in
    ''|*[!0-9]*) return 1 ;;
    *) (( $1 >= 1 && $1 <= 28 )) ;;
  esac
}

prompt_time() {
  local hour_var="$1"
  local minute_var="$2"
  local label="$3"
  local default_value="$4"
  local value hour minute
  while true; do
    prompt_default value "$label, HH:MM" "$default_value"
    case "$value" in
      [0-9]:[0-5][0-9]) hour="${value%%:*}"; minute="${value#*:}" ;;
      [0-2][0-9]:[0-5][0-9]) hour="${value%%:*}"; minute="${value#*:}" ;;
      *) printf 'Please enter time as HH:MM, for example 09:00.\n'; continue ;;
    esac
    hour=$((10#$hour))
    minute=$((10#$minute))
    if is_hour "$hour" && is_minute "$minute"; then
      printf -v "$hour_var" '%s' "$hour"
      printf -v "$minute_var" '%s' "$minute"
      return 0
    fi
    printf 'Please enter a valid 24-hour time.\n'
  done
}

prompt_weekday() {
  local var_name="$1"
  local value
  while true; do
    prompt_default value "Weekly report day, 1=Mon ... 7=Sun" "1"
    if is_weekday "$value"; then
      printf -v "$var_name" '%s' "$value"
      return 0
    fi
    printf 'Please enter 1 to 7.\n'
  done
}

prompt_monthday() {
  local var_name="$1"
  local value
  while true; do
    prompt_default value "Monthly report day, 1-28" "1"
    if is_monthday "$value"; then
      printf -v "$var_name" '%s' "$value"
      return 0
    fi
    printf 'Please enter 1 to 28. 29-31 are avoided so every month works.\n'
  done
}

prompt_check_interval() {
  local value
  while true; do
    prompt_default value "Alert check interval: 1=hourly, 2=every 30 minutes" "1"
    case "$value" in
      1) CHECK_CRON_MINUTE="5"; CHECK_CRON_HOUR="*"; return 0 ;;
      2) CHECK_CRON_MINUTE="*/30"; CHECK_CRON_HOUR="*"; return 0 ;;
      *) printf 'Please choose 1 or 2.\n' ;;
    esac
  done
}

prompt_uint() {
  local var_name="$1"
  local label="$2"
  local default_value="$3"
  local value
  while true; do
    prompt_default value "$label" "$default_value"
    case "$value" in
      ''|*[!0-9]*)
        printf 'Please enter an integer.\n'
        ;;
      0)
        printf 'Please enter a value greater than 0.\n'
        ;;
      *)
        printf -v "$var_name" '%s' "$value"
        return 0
        ;;
    esac
  done
}

escape_config_value() {
  printf '%s' "$1" | sed 's/"/\\"/g'
}

write_config() {
  local tmp
  tmp="$(mktemp)"
  {
    printf '# Generated by vps-traffic-guard install.sh\n'
    printf 'VPS_NAME="%s"\n' "$(escape_config_value "$VPS_NAME")"
    printf 'PUSH_CHANNEL=%s\n' "$PUSH_CHANNEL"
    printf 'TG_BOT_TOKEN="%s"\n' "$(escape_config_value "${TG_BOT_TOKEN:-}")"
    printf 'TG_CHAT_ID="%s"\n' "$(escape_config_value "${TG_CHAT_ID:-}")"
    printf 'BARK_URL="%s"\n' "$(escape_config_value "${BARK_URL:-}")"
    printf 'TRAFFIC_LIMIT_GB=%s\n' "$TRAFFIC_LIMIT_GB"
    printf 'ALERT_PERCENT=%s\n' "$ALERT_PERCENT"
    printf 'IFACE=%s\n' "$IFACE"
    printf 'STATE_DIR=/var/lib/vps-traffic-monitor\n'
    printf 'TIMEZONE=%s\n' "$TIMEZONE"
  } > "$tmp"
  run_as_root install -m 600 "$tmp" "$CONFIG_FILE"
  rm -f "$tmp"
}

install_script() {
  local source_file
  source_file="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/vps-traffic-monitor.sh"
  if [[ -f "$source_file" ]]; then
    run_as_root install -m 755 "$source_file" "$INSTALL_BIN"
  else
    need_cmd curl
    local tmp
    tmp="$(mktemp)"
    curl -fsSL "$REPO_RAW_BASE/vps-traffic-monitor.sh" -o "$tmp"
    run_as_root install -m 755 "$tmp" "$INSTALL_BIN"
    rm -f "$tmp"
  fi
}

install_cron() {
  local current tmp
  tmp="$(mktemp)"
  current="$(mktemp)"
  crontab -l > "$current" 2>/dev/null || true

  awk -v begin="$CRON_MARK_BEGIN" -v end="$CRON_MARK_END" '
    $0 == begin { skip = 1; next }
    $0 == end { skip = 0; next }
    skip != 1 { print }
  ' "$current" > "$tmp"

  {
    printf '%s\n' "$CRON_MARK_BEGIN"
    printf '%s %s * * * %s --config %s --check\n' "$CHECK_CRON_MINUTE" "$CHECK_CRON_HOUR" "$INSTALL_BIN" "$CONFIG_FILE"
    printf '%s %s * * * %s --config %s --daily\n' "$DAILY_MINUTE" "$DAILY_HOUR" "$INSTALL_BIN" "$CONFIG_FILE"
    printf '%s %s * * %s %s --config %s --weekly\n' "$WEEKLY_MINUTE" "$WEEKLY_HOUR" "$WEEKLY_DAY" "$INSTALL_BIN" "$CONFIG_FILE"
    printf '%s %s %s * * %s --config %s --monthly\n' "$MONTHLY_MINUTE" "$MONTHLY_HOUR" "$MONTHLY_DAY" "$INSTALL_BIN" "$CONFIG_FILE"
    printf '%s\n' "$CRON_MARK_END"
  } >> "$tmp"

  crontab "$tmp"
  rm -f "$tmp" "$current"
}

main() {
  need_cmd awk
  need_cmd crontab
  need_cmd sed

  printf 'vps-traffic-guard interactive installer\n\n'

  default_name="$(hostname 2>/dev/null || printf 'my-vps')"
  prompt_default VPS_NAME "VPS display name" "$default_name"
  prompt_uint TRAFFIC_LIMIT_GB "Monthly traffic quota in GiB" "1024"
  prompt_uint ALERT_PERCENT "Alert when monthly usage reaches percent" "80"
  prompt_default IFACE "Network interface, use auto for most VPS/Oracle VPS" "auto"
  prompt_default TIMEZONE "Timezone" "Asia/Shanghai"
  prompt_check_interval
  prompt_time DAILY_HOUR DAILY_MINUTE "Daily report time" "09:00"
  prompt_weekday WEEKLY_DAY
  prompt_time WEEKLY_HOUR WEEKLY_MINUTE "Weekly report time" "09:05"
  prompt_monthday MONTHLY_DAY
  prompt_time MONTHLY_HOUR MONTHLY_MINUTE "Monthly report time" "09:10"

  while true; do
    read -r -p "Push channel: 1) Telegram Bot  2) Bark [1]: " push_choice
    push_choice="${push_choice:-1}"
    case "$push_choice" in
      1)
        PUSH_CHANNEL="telegram"
        prompt_required TG_BOT_TOKEN "Telegram bot token"
        prompt_required TG_CHAT_ID "Telegram chat id"
        BARK_URL=""
        break
        ;;
      2)
        PUSH_CHANNEL="bark"
        prompt_required BARK_URL "Bark URL, for example https://api.day.app/YOUR_KEY"
        TG_BOT_TOKEN=""
        TG_CHAT_ID=""
        break
        ;;
      *)
        printf 'Please choose 1 or 2.\n'
        ;;
    esac
  done

  install_script
  write_config
  install_cron

  printf '\nInstalled.\n'
  printf 'Config: %s\n' "$CONFIG_FILE"
  printf 'Command: %s\n\n' "$INSTALL_BIN"
  printf 'Testing push channel now...\n'
  "$INSTALL_BIN" --config "$CONFIG_FILE" --test-push
  printf '\nTesting traffic detection without sending another push...\n'
  "$INSTALL_BIN" --config "$CONFIG_FILE" --dry-run --check || true
  printf '\nDone. Cron has been installed for hourly checks plus daily, weekly, and monthly reports.\n'
}

main "$@"